[package]
name = "notelog"
version = "0.1.0"
edition = "2024"

[dependencies]
atty = "0.2.14"
chrono = "0.4.41"
clap = { version = "4.5.37", features = ["derive"] }
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.8.26"
tempfile = "3.19.1"
thiserror = "2.0.12"
